defmodule OpalCoreWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :opal_core

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_opal_core_key",
    signing_salt: "7Ny9BQI+",
    same_site: "Lax"
  ]

  socket "/socket", OpalCoreWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :opal_core,
    gzip: not code_reloading?,
    only: OpalCoreWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :opal_core
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OpalCoreWeb.Plugs.FetchCookies
  plug OpalCoreWeb.Plugs.Cors
  # Tunnel mode: allow *.ngrok-free.app / *.ngrok.io (not a blanket disable).
  plug OpalCoreWeb.Plugs.PublicHost
  plug OpalCoreWeb.Router
end
