#!/usr/bin/env bash
# Start or adopt ngrok tunnels; write ~/.opal/tunnel.env (never commit).
# Free ngrok: one agent. Prefer FE(:5173) tunnel + Vite proxy for /health,/webhooks,/api,/invite.
set -euo pipefail

OPAL_DIR="${HOME}/.opal"
ENV_FILE="${OPAL_DIR}/tunnel.env"
API_PORT="${OPAL_API_PORT:-4000}"
FE_PORT="${OPAL_FE_PORT:-5173}"
mkdir -p "${OPAL_DIR}"

if ! command -v ngrok >/dev/null 2>&1; then
  echo "BLOCKED: ngrok not installed. brew install ngrok — or cloudflared (docs/GOING_LIVE.md)"
  exit 1
fi

if ! ngrok config check >/dev/null 2>&1; then
  echo "BLOCKED: ngrok authtoken missing. Founder: https://dashboard.ngrok.com → ngrok config add-authtoken <token>"
  exit 1
fi

fetch_tunnels_json() {
  for port in 4040 4041 4042; do
    if curl -fsS "http://127.0.0.1:${port}/api/tunnels" 2>/dev/null; then
      return 0
    fi
  done
  return 1
}

pick_url_for_local_port() {
  local want="$1"
  python3 -c "
import json,sys
want=sys.argv[1]
raw=sys.stdin.read()
if not raw.strip():
  sys.exit(0)
data=json.loads(raw)
for t in data.get('tunnels',[]):
  cfg=t.get('config') or {}
  addr=str(cfg.get('addr') or '')
  pub=t.get('public_url') or ''
  if not pub.startswith('https://'):
    continue
  if addr.endswith(':'+want) or 'localhost:'+want in addr or '127.0.0.1:'+want in addr:
    print(pub); sys.exit(0)
" "$want" 2>/dev/null || true
}

TUNNELS_JSON="$(fetch_tunnels_json || true)"
API_URL=""
FE_URL=""
if [[ -n "${TUNNELS_JSON}" ]]; then
  API_URL="$(printf '%s' "$TUNNELS_JSON" | pick_url_for_local_port "$API_PORT")"
  FE_URL="$(printf '%s' "$TUNNELS_JSON" | pick_url_for_local_port "$FE_PORT")"
fi

# Free-tier strategy: if FE tunnel exists and API does not, use FE as PUBLIC_BASE_URL
# (Vite proxies /health /webhooks /api /invite → Phoenix :4000).
if [[ -z "$API_URL" && -n "$FE_URL" ]]; then
  echo "Adopting existing FE tunnel as PUBLIC_BASE_URL (Vite proxy → Phoenix)."
  API_URL="$FE_URL"
fi

if [[ -z "$API_URL" && -z "$FE_URL" ]]; then
  echo "Starting ngrok http ${FE_PORT} (FE + proxied API) in background…"
  nohup ngrok http --log=stdout "${FE_PORT}" >"${OPAL_DIR}/ngrok-fe.log" 2>&1 &
  echo $! >"${OPAL_DIR}/ngrok-fe.pid"
  sleep 2
  for _ in $(seq 1 30); do
    TUNNELS_JSON="$(fetch_tunnels_json || true)"
    FE_URL="$(printf '%s' "$TUNNELS_JSON" | pick_url_for_local_port "$FE_PORT")"
    [[ -n "$FE_URL" ]] && break
    sleep 0.5
  done
  API_URL="$FE_URL"
fi

if [[ -z "$API_URL" ]]; then
  echo "FAILED: no public URL. Check ngrok agent / free-tier single-endpoint limit."
  echo "Manual: write OPAL_TUNNEL_API_URL + OPAL_PUBLIC_BASE_MODE=tunnel to ${ENV_FILE}"
  exit 1
fi

LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo 127.0.0.1)"
FE_URL="${FE_URL:-$API_URL}"

cat >"${ENV_FILE}" <<EOF
# Generated by scripts/opal_tunnel_start.sh — DO NOT COMMIT
OPAL_PUBLIC_BASE_MODE=tunnel
OPAL_TUNNEL_API_URL=${API_URL}
OPAL_PUBLIC_BASE_URL=${API_URL}
OPAL_TUNNEL_FE_URL=${FE_URL}
OPAL_PUBLIC_FE_BASE_URL=${FE_URL}
OPAL_LAN_IP=${LAN_IP}
OPAL_TWILIO_VERIFY_STATUS_CALLBACK=${API_URL}/webhooks/twilio/verify
EOF

chmod 600 "${ENV_FILE}"
echo "Wrote ${ENV_FILE}"
echo "PUBLIC_BASE_URL: ${API_URL}"
echo "FE tunnel:        ${FE_URL}"
echo "Twilio callback:  ${API_URL}/webhooks/twilio/verify"
echo "Verify: curl -fsS ${API_URL}/health"
