import Config

# Configure your database
config :opal_core, OpalCore.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "opal_core_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Bind all interfaces so Docker port publishing works; host-local still fine.
config :opal_core, OpalCoreWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "vH43j3nmLPGzmhNFP+uTs3cwNk+s2r/6F58t0jgFJxveCa6HLbhdc3AOVvHe5+2D",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :opal_core, dev_routes: true

# Synthetic development auth ONLY — never enable in production config
config :opal_core, :dev_auth_enabled, true
# Development ergonomics for synthetic SMS codes (never enable in prod)
config :opal_core, :synthetic_provider_expose_code, true
# Local dev allows any +1 number (synthetic code defaults to 000000).
config :opal_core, :synthetic_fixture_only, false
# Founder-walk communication seed via existing Messages owner (opt-in client flag required).
config :opal_core, :allow_founder_communication_seed, true

config :opal_core, :ai_service_url, System.get_env("OPAL_AI_URL") || "http://127.0.0.1:8000"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
